version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - VITE_API_BASE_URL=http://backend:8000
